"""Samplers: one ODE step, expressed as a function of the model output.

Every sampler here obeys the same contract:

    ``step(model_output, x_t, sigma_t, sigma_next) -> x_next``

plus whatever small state the solver itself carries between steps. Nothing in a
sampler knows about a model, a pipeline, a codec, or a prompt. That is the whole
design decision, and it buys three things:

* **Training-time validation and production serving run the identical code.** A
  validation sample generated inside a training step and a sample generated by
  the serving pipeline differ only in who called ``step``.
* **Reinforcement learning can reuse the loop.** Flow-GRPO and its relatives need
  to convert the sampling ODE into an SDE and evaluate the log-probability of the
  transition they took. That requires the noise injection to be *visible* rather
  than hidden inside a scheduler object, which is why
  :class:`EulerAncestralSampler` exposes its split and its noise explicitly.
* **A sampler is testable in isolation.** With a constant velocity field the
  exact answer is known in closed form, and every solver here must reproduce it.

**Conventions.** ``sigma`` is flow time in ``[0, 1]`` (see
:mod:`avgen.infer.schedule`), ``x_t`` is the noisy latent grid, and
``model_output`` is the predicted velocity ``v = noise - clean = dx/dt``. Two
conversions recur and are exact for the linear interpolant, not approximations:

    ``x0 = x_t - sigma_t * v``       (the clean-sample prediction)
    ``eps = x_t + (1 - sigma_t) * v``  (the noise prediction)

Samplers operate on the dense latent grid rather than on a
:class:`~avgen.core.tokens.TokenStream`. The stream is the model's interior
representation; by the time the sampler sees a prediction it has been unfolded,
and a grid is the shape that a codec, a callback, and a saved intermediate all
want.
"""

from __future__ import annotations

import math
from collections.abc import Callable, Mapping
from dataclasses import dataclass
from typing import Any, Protocol, TypeVar, runtime_checkable

import torch

__all__ = [
    "DPMSolverPlusPlus2M",
    "EulerAncestralSampler",
    "EulerSampler",
    "HeunSampler",
    "ResMultistepSampler",
    "Sampler",
    "SamplerConfig",
    "build_sampler",
    "list_samplers",
    "register_sampler",
    "to_epsilon",
    "to_x0",
]

#: Clamp used when a solver needs ``log(sigma)`` or ``log(1 - sigma)``. The
#: schedule legitimately contains 0.0 and may contain 1.0, and both are poles of
#: the exponential-integrator parameterisation. Clamping rather than special-
#: casing keeps the coefficient finite and, because the affected steps fall back
#: to first order anyway, changes no result.
_LOG_FLOOR = 1e-7


def to_x0(x_t: torch.Tensor, velocity: torch.Tensor, sigma: float) -> torch.Tensor:
    """Convert a velocity prediction into a clean-sample prediction.

    Exact for the rectified-flow interpolant: substituting
    ``x_t = (1 - s) * x0 + s * eps`` and ``v = eps - x0`` into ``x_t - s * v``
    cancels ``eps`` entirely and leaves ``x0``.

    Args:
        x_t: Noisy sample.
        velocity: Predicted velocity at ``sigma``.
        sigma: Flow time of ``x_t``.

    Returns:
        The implied clean sample.
    """
    return x_t - sigma * velocity


def to_epsilon(
    x_t: torch.Tensor, velocity: torch.Tensor, sigma: float
) -> torch.Tensor:
    """Convert a velocity prediction into a noise prediction.

    Args:
        x_t: Noisy sample.
        velocity: Predicted velocity at ``sigma``.
        sigma: Flow time of ``x_t``.

    Returns:
        The implied noise.
    """
    return x_t + (1.0 - sigma) * velocity


#: Signature of the callback a multi-evaluation solver uses to query the model at
#: an intermediate point: ``(x, sigma) -> velocity``.
Denoiser = Callable[[torch.Tensor, float], torch.Tensor]


@dataclass(frozen=True, slots=True)
class SamplerConfig:
    """Everything that parameterises a sampler.

    One config type for every sampler rather than one per solver. The alternative
    — a config class per sampler, resolved by the registry — was rejected because
    it makes the CLI and the YAML loader carry a discriminated union for a
    handful of scalars, and because a user switching ``euler`` to ``heun`` should
    not have to rewrite the config block.

    Args:
        name: Registered sampler name.
        eta: Stochasticity for ancestral sampling. ``0.0`` makes
            :class:`EulerAncestralSampler` reduce *exactly* to Euler, which is
            the property the tests assert. ``1.0`` injects the maximum noise the
            ancestral decomposition allows.
        s_noise: Multiplier on the injected noise. Values slightly above 1.0 are
            a folk remedy for over-smooth samples; it is not principled and it
            breaks the SDE log-probability the RL subsystem computes, so leave it
            at 1.0 unless you know why you are moving it.
        lower_order_final: Whether the last step drops to first order. It should:
            the exponential-integrator coefficients have a pole at ``sigma = 0``,
            and a first-order step there is the *exact* solution under the
            solver's own frozen-prediction assumption, not an approximation.

    Raises:
        ValueError: If ``name`` is empty or a coefficient is out of range.
    """

    name: str = "euler"
    eta: float = 0.0
    s_noise: float = 1.0
    lower_order_final: bool = True

    def __post_init__(self) -> None:
        """Validate the coefficients."""
        if not self.name or self.name.strip() != self.name:
            raise ValueError(
                f"name must be a non-empty trimmed string; got {self.name!r}"
            )
        if not math.isfinite(self.eta) or not 0.0 <= self.eta <= 1.0:
            raise ValueError(f"eta must be in [0, 1]; got {self.eta!r}")
        if not math.isfinite(self.s_noise) or self.s_noise < 0.0:
            raise ValueError(
                f"s_noise must be finite and non-negative; got {self.s_noise!r}"
            )

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-safe representation for pinning into a sample."""
        return {
            "name": self.name,
            "eta": self.eta,
            "s_noise": self.s_noise,
            "lower_order_final": self.lower_order_final,
        }

    @classmethod
    def from_dict(cls, values: Mapping[str, Any]) -> SamplerConfig:
        """Rebuild a config from :meth:`to_dict` output.

        Args:
            values: The mapping.

        Returns:
            The restored config.
        """
        keys = ("name", "eta", "s_noise", "lower_order_final")
        return cls(**{key: values[key] for key in keys if key in values})


@runtime_checkable
class Sampler(Protocol):
    """One step of an ODE (or SDE) solver over the flow schedule.

    Implementations are stateful only in the sense that a multistep solver
    remembers its previous prediction. That state is per-generation, so a sampler
    instance belongs to one sampling run and :meth:`reset` starts a new one.
    """

    @property
    def evaluations_per_step(self) -> int:
        """Model forward passes this solver needs per step.

        A budget of ``N`` steps with a two-evaluation solver costs the same as
        ``2N`` steps with a one-evaluation solver, which is the comparison that
        actually matters when choosing between them.
        """
        ...

    @property
    def is_stochastic(self) -> bool:
        """Whether this solver injects noise and therefore needs a generator."""
        ...

    def reset(self) -> None:
        """Discard multistep history before starting a new generation."""
        ...

    def step(
        self,
        model_output: torch.Tensor,
        x_t: torch.Tensor,
        sigma_t: float,
        sigma_next: float,
        *,
        denoise: Denoiser | None = None,
        generator: torch.Generator | None = None,
    ) -> torch.Tensor:
        """Advance the sample from ``sigma_t`` to ``sigma_next``.

        Args:
            model_output: Predicted velocity at ``(x_t, sigma_t)``.
            x_t: Current noisy sample.
            sigma_t: Current flow time.
            sigma_next: Target flow time, strictly below ``sigma_t``.
            denoise: Callback to evaluate the model at an intermediate point.
                Required by solvers whose ``evaluations_per_step`` exceeds one,
                ignored by the rest.
            generator: Randomness source. Required by stochastic solvers; passing
                ``None`` to one is an error rather than a silent fallback to the
                global RNG, which would break the seed-reproducibility contract.

        Returns:
            The sample at ``sigma_next``.

        Raises:
            ValueError: If a required ``denoise`` or ``generator`` is missing, or
                if ``sigma_next`` is not below ``sigma_t``.
        """
        ...


_SAMPLERS: dict[str, Callable[[SamplerConfig], Sampler]] = {}

#: Bound to the decorated class so the registry decorator is transparent to the
#: type checker: ``EulerSampler`` stays a class, not a ``Callable``.
_FactoryT = TypeVar("_FactoryT", bound=Callable[..., Any])


def register_sampler(name: str) -> Callable[[_FactoryT], _FactoryT]:
    """Register a sampler factory under a name.

    Args:
        name: Registry key.

    Returns:
        A decorator that registers and returns the factory unchanged.

    Raises:
        ValueError: If ``name`` is empty, untrimmed, or already registered.
            Silent replacement is refused because a pinned generation config
            naming a sampler must resolve to the same solver forever.
    """
    if not name or name.strip() != name:
        raise ValueError(f"name must be a non-empty trimmed string; got {name!r}")
    if name in _SAMPLERS:
        raise ValueError(f"sampler {name!r} is already registered")

    def decorator(factory: _FactoryT) -> _FactoryT:
        _SAMPLERS[name] = factory
        return factory

    return decorator


def build_sampler(config: SamplerConfig | str) -> Sampler:
    """Construct a sampler from a config or a bare name.

    Args:
        config: A :class:`SamplerConfig`, or a name to use with defaults.

    Returns:
        A fresh sampler instance. Never shared: multistep state belongs to one
        generation.

    Raises:
        KeyError: If the name is not registered.
    """
    resolved = SamplerConfig(name=config) if isinstance(config, str) else config
    factory = _SAMPLERS.get(resolved.name)
    if factory is None:
        raise KeyError(
            f"unknown sampler {resolved.name!r}; registered: "
            f"{', '.join(list_samplers())}"
        )
    return factory(resolved)


def list_samplers() -> tuple[str, ...]:
    """Return the registered sampler names, sorted."""
    return tuple(sorted(_SAMPLERS))


class _BaseSampler:
    """Shared validation and state handling for the shipped solvers."""

    __slots__ = ("config",)

    def __init__(self, config: SamplerConfig | None = None) -> None:
        self.config = config or SamplerConfig()

    @property
    def evaluations_per_step(self) -> int:
        """Model forward passes per step."""
        return 1

    @property
    def is_stochastic(self) -> bool:
        """Whether this solver injects noise."""
        return False

    def reset(self) -> None:
        """Discard multistep history. A no-op for single-step solvers."""

    @staticmethod
    def _check(sigma_t: float, sigma_next: float) -> None:
        """Reject a step that does not move forward in time."""
        if not math.isfinite(sigma_t) or not math.isfinite(sigma_next):
            raise ValueError(
                f"sigmas must be finite; got sigma_t={sigma_t!r}, "
                f"sigma_next={sigma_next!r}"
            )
        if sigma_next >= sigma_t:
            raise ValueError(
                f"sigma_next={sigma_next} must be below sigma_t={sigma_t}; "
                "the sampler integrates from noise towards clean"
            )


@register_sampler("euler")
class EulerSampler(_BaseSampler):
    """First-order explicit Euler.

    ``x_next = x_t + (sigma_next - sigma_t) * v``.

    For a *perfectly* trained rectified flow this is not an approximation: the
    probability path is a straight line, the velocity along it is constant, and
    one Euler step of any size lands exactly on the target. Everything more
    elaborate in this module exists to compensate for the fact that a real
    model's velocity field is only approximately constant along the path, which
    is a statement about the model rather than about the ODE.

    Euler is therefore the right default, the right baseline, and the right thing
    to reach for when a fancier solver produces artifacts — with a well-trained
    flow model at 30+ steps the difference is usually invisible.
    """

    __slots__ = ()

    def step(
        self,
        model_output: torch.Tensor,
        x_t: torch.Tensor,
        sigma_t: float,
        sigma_next: float,
        *,
        denoise: Denoiser | None = None,
        generator: torch.Generator | None = None,
    ) -> torch.Tensor:
        """Advance one Euler step.

        Args:
            model_output: Predicted velocity at ``(x_t, sigma_t)``.
            x_t: Current noisy sample.
            sigma_t: Current flow time.
            sigma_next: Target flow time.
            denoise: Unused.
            generator: Unused.

        Returns:
            The sample at ``sigma_next``.

        Raises:
            ValueError: If ``sigma_next`` is not below ``sigma_t``.
        """
        del denoise, generator
        self._check(sigma_t, sigma_next)
        return x_t + (sigma_next - sigma_t) * model_output


@register_sampler("heun")
class HeunSampler(_BaseSampler):
    """Second-order Heun (explicit trapezoid), two evaluations per step.

    Takes an Euler step to get a provisional endpoint, evaluates the velocity
    there, and averages the two velocities. The averaging is what makes it
    second order: Euler assumes the velocity at the *start* of the interval holds
    throughout, and Heun corrects that with the velocity at the end.

    The cost is exact and unforgiving: two forward passes per step. Compare it
    against Euler at *equal model evaluations* — 15 Heun steps versus 30 Euler
    steps — not at equal step counts, or the comparison is meaningless.

    On the last step, when ``sigma_next`` is zero, the correction is still valid
    and is applied; there is no pole here, unlike in the exponential-integrator
    solvers.
    """

    __slots__ = ()

    @property
    def evaluations_per_step(self) -> int:
        """Two: one at the interval start, one at the provisional endpoint."""
        return 2

    def step(
        self,
        model_output: torch.Tensor,
        x_t: torch.Tensor,
        sigma_t: float,
        sigma_next: float,
        *,
        denoise: Denoiser | None = None,
        generator: torch.Generator | None = None,
    ) -> torch.Tensor:
        """Advance one Heun step.

        Args:
            model_output: Predicted velocity at ``(x_t, sigma_t)``.
            x_t: Current noisy sample.
            sigma_t: Current flow time.
            sigma_next: Target flow time.
            denoise: Callback evaluating the model at the provisional endpoint.
                Required.
            generator: Unused.

        Returns:
            The sample at ``sigma_next``.

        Raises:
            ValueError: If ``denoise`` is missing or the step does not advance.
        """
        del generator
        self._check(sigma_t, sigma_next)
        if denoise is None:
            raise ValueError(
                "heun requires a denoise callback: it evaluates the model a "
                "second time at the provisional endpoint. Pass one, or use "
                "euler if only one evaluation per step is affordable."
            )
        delta = sigma_next - sigma_t
        probe = x_t + delta * model_output
        second = denoise(probe, sigma_next)
        return x_t + delta * 0.5 * (model_output + second)


@register_sampler("dpmpp_2m")
class DPMSolverPlusPlus2M(_BaseSampler):
    """DPM-Solver++(2M): second-order multistep in data-prediction form.

    Second order for the price of *one* evaluation per step, by reusing the
    previous step's clean-sample prediction instead of taking a fresh one — the
    multistep trade against Heun's single-step second order. In exchange it needs
    a warm-up step and it is less stable if the schedule's step sizes vary
    wildly, because the linear extrapolation assumes the two intervals are
    comparable.

    Working in ``x0`` space rather than ``eps`` space is the "++" of the name and
    it matters most exactly where video models live: at high guidance scales the
    noise prediction is large and its extrapolation error compounds, while the
    clean-sample prediction stays bounded by the data.

    The update is written in a form free of the ``log`` poles at ``sigma = 1``
    and ``sigma = 0``::

        x_next = (sigma_next / sigma_t) * (x_t - alpha_t * D) + alpha_next * D

    with ``alpha = 1 - sigma`` and ``D`` the extrapolated clean prediction. Only
    the extrapolation *weight* needs the log-space step sizes, and a clamp there
    degrades the affected step to first order rather than producing an infinity.
    """

    __slots__ = ("_previous_h", "_previous_x0")

    def __init__(self, config: SamplerConfig | None = None) -> None:
        super().__init__(config)
        self._previous_x0: torch.Tensor | None = None
        self._previous_h: float | None = None

    def reset(self) -> None:
        """Discard the previous clean-sample prediction."""
        self._previous_x0 = None
        self._previous_h = None

    def step(
        self,
        model_output: torch.Tensor,
        x_t: torch.Tensor,
        sigma_t: float,
        sigma_next: float,
        *,
        denoise: Denoiser | None = None,
        generator: torch.Generator | None = None,
    ) -> torch.Tensor:
        """Advance one multistep step.

        Args:
            model_output: Predicted velocity at ``(x_t, sigma_t)``.
            x_t: Current noisy sample.
            sigma_t: Current flow time.
            sigma_next: Target flow time.
            denoise: Unused.
            generator: Unused.

        Returns:
            The sample at ``sigma_next``.

        Raises:
            ValueError: If the step does not advance.
        """
        del denoise, generator
        self._check(sigma_t, sigma_next)
        x0 = to_x0(x_t, model_output, sigma_t)
        step_h = _log_step(sigma_t, sigma_next)

        final = sigma_next == 0.0 and self.config.lower_order_final
        if self._previous_x0 is None or self._previous_h is None or final:
            prediction = x0
        else:
            # weight = h / (2 * h_last); the DPM-Solver++(2M) coefficient
            # (1 + 1/(2r)) with r = h_last / h, rearranged so that an enormous
            # h_last (which is what the clamped pole at sigma=1 produces) makes
            # the weight vanish and the step degrade to first order, instead of
            # producing an inf/inf.
            weight = step_h / (2.0 * self._previous_h)
            prediction = (1.0 + weight) * x0 - weight * self._previous_x0

        alpha_t = 1.0 - sigma_t
        alpha_next = 1.0 - sigma_next
        ratio = sigma_next / max(sigma_t, _LOG_FLOOR)
        x_next = ratio * (x_t - alpha_t * prediction) + alpha_next * prediction

        self._previous_x0 = x0
        self._previous_h = step_h
        return x_next


@register_sampler("res_multistep")
class ResMultistepSampler(_BaseSampler):
    """Refined exponential solver, second-order multistep.

    Same skeleton as :class:`DPMSolverPlusPlus2M` — one evaluation per step, a
    linear extrapolation of the clean-sample prediction over the log-space
    interval — but it integrates that extrapolation *exactly* instead of
    collapsing it into a single averaged coefficient.

    Writing ``tau`` for position within the step and ``h`` for its log-space
    length, the exponential integrator needs two moments of the weight
    ``exp(tau - h)``::

        phi_1 = 1 - exp(-h)            (the constant term)
        phi_2 = h - 1 + exp(-h)        (the linear term)

    DPM-Solver++(2M) folds the linear term into ``phi_1`` with the midpoint
    coefficient ``1 + h / (2 * h_last)``, which agrees to second order. Using the
    true ``phi_2`` keeps the higher-order terms the midpoint approximation drops,
    and the difference shows up as better behaviour at aggressive step counts —
    which is the regime this solver exists for.

    Both moments are evaluated through ``expm1`` because ``h - 1 + exp(-h)`` is
    ``h**2 / 2`` for small ``h`` and would otherwise be computed as the
    difference of two nearly equal numbers, losing most of its significant
    digits exactly where the step is smallest.
    """

    __slots__ = ("_previous_h", "_previous_x0")

    def __init__(self, config: SamplerConfig | None = None) -> None:
        super().__init__(config)
        self._previous_x0: torch.Tensor | None = None
        self._previous_h: float | None = None

    def reset(self) -> None:
        """Discard the previous clean-sample prediction."""
        self._previous_x0 = None
        self._previous_h = None

    def step(
        self,
        model_output: torch.Tensor,
        x_t: torch.Tensor,
        sigma_t: float,
        sigma_next: float,
        *,
        denoise: Denoiser | None = None,
        generator: torch.Generator | None = None,
    ) -> torch.Tensor:
        """Advance one exponential-integrator step.

        Args:
            model_output: Predicted velocity at ``(x_t, sigma_t)``.
            x_t: Current noisy sample.
            sigma_t: Current flow time.
            sigma_next: Target flow time.
            denoise: Unused.
            generator: Unused.

        Returns:
            The sample at ``sigma_next``.

        Raises:
            ValueError: If the step does not advance.
        """
        del denoise, generator
        self._check(sigma_t, sigma_next)
        x0 = to_x0(x_t, model_output, sigma_t)
        step_h = _log_step(sigma_t, sigma_next)

        alpha_t = 1.0 - sigma_t
        alpha_next = 1.0 - sigma_next
        ratio = sigma_next / max(sigma_t, _LOG_FLOOR)
        final = sigma_next == 0.0 and self.config.lower_order_final

        if self._previous_x0 is None or self._previous_h is None or final:
            # First order is the exact integral of a constant x0 over the step,
            # which is algebraically identical to an Euler step in x-space.
            x_next = ratio * (x_t - alpha_t * x0) + alpha_next * x0
        else:
            phi_1 = -math.expm1(-step_h)
            phi_2 = step_h + math.expm1(-step_h)
            slope = (x0 - self._previous_x0) / self._previous_h
            integral = phi_1 * x0 + phi_2 * slope
            x_next = ratio * x_t + alpha_next * integral

        # State is recorded on every step, including the first-order ones: the
        # next step's extrapolation needs a predecessor regardless of how this
        # one was solved.
        self._previous_x0 = x0
        self._previous_h = step_h
        return x_next


@register_sampler("euler_ancestral")
class EulerAncestralSampler(_BaseSampler):
    """Stochastic Euler: descend part-way, then renoise.

    Each step is split into a deterministic descent to an intermediate
    ``sigma_down`` and an injection of fresh noise back up to ``sigma_next``. The
    injected noise gives the sampler a chance to escape a trajectory the
    deterministic solver has committed to, which is why ancestral sampling often
    looks more detailed at low step counts — and why it is not reproducible
    across a change of step count the way a pure ODE solver is.

    **This is the ODE-to-SDE conversion the RL subsystem needs.** Policy-gradient
    methods over diffusion (Flow-GRPO, DDPO and relatives) treat sampling as a
    sequence of stochastic actions and need the log-probability of the transition
    that was actually taken. That is only well defined if the transition is
    stochastic and its distribution is known, so the split and the injected noise
    are exposed rather than buried: :meth:`ancestral_split` gives the standard
    deviation of the transition, and :meth:`step_with_noise` returns the exact
    noise sample that was used.

    ``eta = 0`` gives ``sigma_up = 0`` and ``sigma_down = sigma_next``, so the
    step becomes *bit-identical* to :class:`EulerSampler`. That equivalence is
    load-bearing: it is what lets an RL run share one code path with the
    deterministic evaluation it is measured against.
    """

    __slots__ = ()

    @property
    def is_stochastic(self) -> bool:
        """True unless ``eta`` is zero."""
        return self.config.eta > 0.0

    def ancestral_split(self, sigma_t: float, sigma_next: float) -> tuple[float, float]:
        """Split a step into a deterministic part and a noise part.

        The variance budget is the k-diffusion ancestral decomposition: the
        largest noise that can be injected while still arriving at ``sigma_next``
        is bounded by ``sigma_next``, and the fraction of it actually used is
        ``eta``. The deterministic target is then pulled down to
        ``sqrt(sigma_next**2 - sigma_up**2)`` so that the two contributions
        recombine to the right total noise level.

        Args:
            sigma_t: Current flow time.
            sigma_next: Target flow time.

        Returns:
            ``(sigma_down, sigma_up)``. ``sigma_up`` is the standard deviation of
            the noise to inject; ``sigma_down`` is where the deterministic step
            lands.
        """
        if self.config.eta <= 0.0 or sigma_next == 0.0 or sigma_t == 0.0:
            # No noise is injectable into a target of zero: the sample must be
            # exactly clean at the end of the schedule.
            return sigma_next, 0.0
        variance_ratio = (sigma_t * sigma_t - sigma_next * sigma_next) / (
            sigma_t * sigma_t
        )
        sigma_up = min(
            sigma_next,
            self.config.eta * sigma_next * math.sqrt(max(variance_ratio, 0.0)),
        )
        sigma_down = math.sqrt(max(sigma_next * sigma_next - sigma_up * sigma_up, 0.0))
        return sigma_down, sigma_up

    def step_with_noise(
        self,
        model_output: torch.Tensor,
        x_t: torch.Tensor,
        sigma_t: float,
        sigma_next: float,
        *,
        generator: torch.Generator | None = None,
        noise: torch.Tensor | None = None,
    ) -> tuple[torch.Tensor, torch.Tensor, float]:
        """Advance one step and return the noise that was injected.

        Args:
            model_output: Predicted velocity at ``(x_t, sigma_t)``.
            x_t: Current noisy sample.
            sigma_t: Current flow time.
            sigma_next: Target flow time.
            generator: Randomness source. Required when noise is to be drawn.
            noise: Pre-drawn unit-variance noise to use instead of drawing. This
                is how an RL trainer replays a trajectory it has already sampled
                and recomputes its log-probability under updated parameters.

        Returns:
            ``(x_next, noise, sigma_up)``. When ``sigma_up`` is zero the returned
            noise is a zero tensor and the step was deterministic.

        Raises:
            ValueError: If noise must be drawn and no generator was supplied, or
                if the step does not advance.
        """
        self._check(sigma_t, sigma_next)
        sigma_down, sigma_up = self.ancestral_split(sigma_t, sigma_next)
        x_next = x_t + (sigma_down - sigma_t) * model_output
        if sigma_up == 0.0:
            return x_next, torch.zeros_like(x_t), 0.0
        if noise is None:
            if generator is None:
                raise ValueError(
                    "euler_ancestral with eta > 0 needs a torch.Generator; "
                    "falling back to the global RNG would break the "
                    "seed-reproducibility contract"
                )
            noise = torch.randn(
                x_t.shape, generator=generator, device=x_t.device, dtype=x_t.dtype
            )
        scale = sigma_up * self.config.s_noise
        return x_next + scale * noise, noise, sigma_up

    def step(
        self,
        model_output: torch.Tensor,
        x_t: torch.Tensor,
        sigma_t: float,
        sigma_next: float,
        *,
        denoise: Denoiser | None = None,
        generator: torch.Generator | None = None,
    ) -> torch.Tensor:
        """Advance one ancestral step.

        Args:
            model_output: Predicted velocity at ``(x_t, sigma_t)``.
            x_t: Current noisy sample.
            sigma_t: Current flow time.
            sigma_next: Target flow time.
            denoise: Unused.
            generator: Randomness source, required when ``eta`` is positive.

        Returns:
            The sample at ``sigma_next``.

        Raises:
            ValueError: If a generator is needed and missing.
        """
        del denoise
        x_next, _, _ = self.step_with_noise(
            model_output, x_t, sigma_t, sigma_next, generator=generator
        )
        return x_next


def _log_step(sigma_t: float, sigma_next: float) -> float:
    """Return the exponential-integrator step size between two flow times.

    ``h = lambda_next - lambda_t`` with ``lambda = log(alpha) - log(sigma)`` and
    ``alpha = 1 - sigma``. Both endpoints of a flow schedule are poles — ``alpha``
    vanishes at ``sigma = 1`` and ``sigma`` vanishes at the end — so both logs are
    floored. The floor is only ever reached on steps that fall back to first
    order, so it changes no result; without it the first and last steps would
    produce infinities that propagate into the extrapolation weight.

    Args:
        sigma_t: Current flow time.
        sigma_next: Target flow time.

    Returns:
        A positive, finite step size.
    """
    alpha_t = max(1.0 - sigma_t, _LOG_FLOOR)
    alpha_next = max(1.0 - sigma_next, _LOG_FLOOR)
    lambda_t = math.log(alpha_t) - math.log(max(sigma_t, _LOG_FLOOR))
    lambda_next = math.log(alpha_next) - math.log(max(sigma_next, _LOG_FLOOR))
    return lambda_next - lambda_t
